### ISSUE TITLE
Remove gunicorn.six import, move to just six

### ISSUE THREAD

**Issue by alibama** [tkp-archive/paperboy#95]
**Describe the bug**
working in ubuntu 18.04
after running the first three commands 
npm install

i get this warning... 
npm WARN ts-jest@23.10.5 requires a peer of jest@>=22 <24 but none is installed. You must install peer dependencies yourself.

npm run build - runs fine
pip install -e .  - says it installs successfully

i ran "python -m paperboy"

and got this error 

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/paperboy-master/paperboy/__main__.py", line 4, in <module>
    main()
  File "/home/ubuntu/paperboy-master/paperboy/server/__init__.py", line 7, in main
    from ..config.application import Paperboy
  File "/home/ubuntu/paperboy-master/paperboy/config/application.py", line 15, in <module>
    from ..server.deploy import FalconDeploy
  File "/home/ubuntu/paperboy-master/paperboy/server/deploy.py", line 7, in <module>
    from .deploy_nix import FalconGunicorn as FalconDeploy  # noqa: F401
  File "/home/ubuntu/paperboy-master/paperboy/server/deploy_nix.py", line 2, in <module>
    from gunicorn.six import iteritems
ModuleNotFoundError: No module named 'gunicorn.six'

any ideas?

**Comment by timkpaine** [comment]
you can install an older gunicorn for now to get around this
https://github.com/benoitc/gunicorn/pull/2083

**Comment by alibama** [comment]
thanks man - great call, should have dug around more to find that
for those on ubuntu

`pip install gunicorn==19`
and then 
`python -m paperboy`
worked fine
